### ISSUE TITLE
Function() should take comma-separated argument lists

### ISSUE THREAD

**Issue by cpcallen** [NeilFraser/CodeCity#95]
Per [§15.3.2.1 of the ES5.1 spec](http://www.ecma-international.org/ecma-262/5.1/#sec-15.3.2.1), `Function` should accept comma-separated argument lists—i.e., `Function('a,b', …)` should be equivalent to `Function('a', 'b', …)` (rather than throwing a SyntaxError, as it presently does).

**Comment by NeilFraser** [comment]
Fixed in #98
